### ISSUE TITLE
ItemStack / Loditeck / Angeles 

### ISSUE THREAD

**Issue by dotpkg** [bizarrealex/future_blacklists#4]
Lol add this skid.

**Comment by bizarrealex** [comment]
In game names?

**Comment by ItsMonkeyyy** [comment]
Arrificials

**Comment by codinglib** [comment]
Think you'll find thats not my ign dumb cunt

**Comment by ItsMonkeyyy** [comment]
shut the fuck up skid
http://prntscr.com/du4284

**Comment by bizarrealex** [comment]
well it is an object!!!!!!!!!!!!!
